### ISSUE TITLE
Замечания к лабораторной 1

### ISSUE THREAD

**Issue by rredbird66** [foblako/PZRL-Second-LAB#1]
1. Ошибка в Makefile из-за которой не получается проверить :/ Ну уже 100 раз всем говорил. Почему в реквизитах цели run нет сборки исполняемого файла? Если вы сначала сделаете make clean, а после этого make run - ничего не заработает.
![изображение](https://github.com/foblako/PZRL-Second-LAB/assets/36138085/b903890e-d741-417d-9a50-b99d0dc93ec2)

**Comment by foblako** [comment]
Ошибка исправлена

**Comment by foblako** [comment]
> 1. Ошибка в Makefile из-за которой не получается проверить :/ Ну уже 100 раз всем говорил. Почему в реквизитах цели run нет сборки исполняемого файла? Если вы сначала сделаете make clean, а после этого make run - ничего не заработает.
>    ![изображение](https://private-user-images.githubusercontent.com/36138085/291005316-b903890e-d741-417d-9a50-b99d0dc93ec2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NDgyMzcsIm5iZiI6MTcwMjc0NzkzNywicGF0aCI6Ii8zNjEzODA4NS8yOTEwMDUzMTYtYjkwMzg5MGUtZDc0MS00MTdkLTlhNTAtYjk5ZDBkYzkzZWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE3MzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNTRjODA2MGI5YmJmMzkxZWIxNTc5MTAxODVkN2M5YTBhMTk3YjliOWMzNWU1MmU4YmQyMmM5ZjBkZjUxZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N5y7n7bXfb7E5nUO2o5M4zOh_AYe5savvER3-8kgEOs)

ошибка исправлена

**Comment by rredbird66** [comment]
Эхх. А без этой ошибки могли б сразу зачесть.
Тут, правда, оператор некорректный, а не числа, ну да и ладно.
![изображение](https://github.com/foblako/PZRL-Second-LAB/assets/36138085/53b74f89-3c9e-4b7f-b8fa-af9eabbb311b)
Лабораторная 2 зачтена.
